//! Golden fixture verification for digest projections, set manifests,
//! canonical timestamp / digest-string forms, and the critical-extension
//! gate (`docs/standards/canonical-encoding-and-digest.md` sections 6, 8,
//! 10, 13, 14). The fixture file is generated by the TypeScript twin and
//! independently re-verified here, byte for byte.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use cognitive_contracts::bundle::{self, BundleAsset};
use cognitive_contracts::canonical;
use cognitive_contracts::projection::{
    assert_no_unknown_critical_extensions, projection_canonical_bytes, projection_digest,
    validate_canonical_timestamp, validate_digest_string, verify_content_digest,
};
use serde_json::Value;
use std::path::PathBuf;

fn fixtures() -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("tests")
        .join("golden")
        .join("digest-and-projection-fixtures.json");
    let raw = std::fs::read_to_string(path).expect("fixture file must exist");
    serde_json::from_str(&raw).expect("fixture file must be valid JSON")
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn excluded_of(fixture: &Value) -> Vec<&str> {
    fixture["digest_excluded"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| p.as_str().unwrap())
        .collect()
}

#[test]
fn projection_positive_fixtures_match() {
    let doc = fixtures();
    let entries = doc["projection_positive"].as_array().unwrap();
    assert!(entries.len() >= 3, "projection coverage shrank");
    for fixture in entries {
        let id = fixture["id"].as_str().unwrap();
        let excluded = excluded_of(fixture);
        let domain = fixture["domain"].as_str().unwrap();
        let bytes = projection_canonical_bytes(&fixture["object"], &excluded)
            .unwrap_or_else(|err| panic!("{id}: projection failed: {err}"));
        assert_eq!(
            String::from_utf8(bytes.clone()).unwrap(),
            fixture["expected_projection_canonical_text"]
                .as_str()
                .unwrap(),
            "projection text mismatch for {id}"
        );
        assert_eq!(
            hex(&bytes),
            fixture["expected_projection_canonical_utf8_hex"]
                .as_str()
                .unwrap(),
            "projection hex mismatch for {id}"
        );
        assert_eq!(
            projection_digest(&fixture["object"], &excluded, domain).unwrap(),
            fixture["expected_digest"].as_str().unwrap(),
            "projection digest mismatch for {id}"
        );
        if fixture["expected_verification"].as_str() == Some("accept") {
            let pointer = fixture["digest_pointer"].as_str().unwrap();
            verify_content_digest(&fixture["object"], &excluded, domain, pointer)
                .unwrap_or_else(|err| panic!("{id}: verification must accept: {err}"));
        }
    }
}

#[test]
fn projection_negative_fixtures_fail_closed() {
    let doc = fixtures();
    let entries = doc["projection_negative"].as_array().unwrap();
    assert!(entries.len() >= 5, "projection negative coverage shrank");
    for fixture in entries {
        let id = fixture["id"].as_str().unwrap();
        let excluded = excluded_of(fixture);
        let domain = fixture["domain"].as_str().unwrap();
        let pointer = fixture["digest_pointer"].as_str().unwrap();
        let err = verify_content_digest(&fixture["object"], &excluded, domain, pointer)
            .expect_err(&format!("{id} must be rejected"));
        assert_eq!(
            err.category(),
            fixture["expected_rejection"].as_str().unwrap(),
            "category mismatch for {id}"
        );
    }
}

fn assets_of(fixture: &Value) -> Vec<BundleAsset> {
    fixture["assets"]
        .as_array()
        .unwrap()
        .iter()
        .map(|a| BundleAsset {
            id: a["id"].as_str().unwrap().to_owned(),
            version: a["version"].as_str().unwrap().to_owned(),
            media_type: a["media_type"].as_str().unwrap().to_owned(),
            content_digest: a["content_digest"].as_str().unwrap().to_owned(),
        })
        .collect()
}

#[test]
fn set_manifest_fixtures_match() {
    let doc = fixtures();
    for fixture in doc["set_manifest_positive"].as_array().unwrap() {
        let id = fixture["id"].as_str().unwrap();
        let assets = assets_of(fixture);
        let domain = fixture["domain"].as_str().unwrap();
        let bytes = bundle::manifest_canonical_bytes(&assets).unwrap();
        assert_eq!(
            String::from_utf8(bytes.clone()).unwrap(),
            fixture["expected_manifest_canonical_text"]
                .as_str()
                .unwrap(),
            "manifest text mismatch for {id}"
        );
        assert_eq!(
            hex(&bytes),
            fixture["expected_manifest_canonical_utf8_hex"]
                .as_str()
                .unwrap(),
            "manifest hex mismatch for {id}"
        );
        assert_eq!(
            bundle::manifest_digest(&assets, domain).unwrap(),
            fixture["expected_digest"].as_str().unwrap(),
            "manifest digest mismatch for {id}"
        );
    }
    for fixture in doc["set_manifest_negative"].as_array().unwrap() {
        let id = fixture["id"].as_str().unwrap();
        let assets = assets_of(fixture);
        let domain = fixture["domain"].as_str().unwrap();
        let err =
            bundle::manifest_digest(&assets, domain).expect_err(&format!("{id} must be rejected"));
        let category = match err {
            bundle::BundleError::DuplicateAssetId(_) => "duplicate-asset-id",
            bundle::BundleError::EmptyBundle => "empty-bundle",
            bundle::BundleError::Canonical(_) => "canonical",
        };
        assert_eq!(
            category,
            fixture["expected_rejection"].as_str().unwrap(),
            "category mismatch for {id}"
        );
    }
}

#[test]
fn timestamp_and_digest_string_fixtures_match() {
    let doc = fixtures();
    for value in doc["timestamp_positive"].as_array().unwrap() {
        let ts = value.as_str().unwrap();
        assert!(
            validate_canonical_timestamp(ts).is_ok(),
            "{ts} must be accepted"
        );
    }
    for fixture in doc["timestamp_negative"].as_array().unwrap() {
        let ts = fixture["value"].as_str().unwrap();
        assert_eq!(
            validate_canonical_timestamp(ts).unwrap_err().category(),
            "invalid-timestamp",
            "{ts} must be rejected ({})",
            fixture["reason"].as_str().unwrap_or("")
        );
    }
    for value in doc["digest_string_positive"].as_array().unwrap() {
        let dg = value.as_str().unwrap();
        assert!(validate_digest_string(dg).is_ok(), "{dg} must be accepted");
    }
    for fixture in doc["digest_string_negative"].as_array().unwrap() {
        let dg = fixture["value"].as_str().unwrap();
        assert_eq!(
            validate_digest_string(dg).unwrap_err().category(),
            "invalid-digest",
            "{dg} must be rejected ({})",
            fixture["reason"].as_str().unwrap_or("")
        );
    }
}

#[test]
fn extension_gate_fixtures_match() {
    let doc = fixtures();
    for fixture in doc["extension_positive"].as_array().unwrap() {
        let id = fixture["id"].as_str().unwrap();
        let supported: Vec<&str> = fixture["supported"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| s.as_str().unwrap())
            .collect();
        assert_no_unknown_critical_extensions(&fixture["object"], &supported)
            .unwrap_or_else(|err| panic!("{id} must be accepted: {err}"));
    }
    for fixture in doc["extension_negative"].as_array().unwrap() {
        let id = fixture["id"].as_str().unwrap();
        let supported: Vec<&str> = fixture["supported"]
            .as_array()
            .unwrap()
            .iter()
            .map(|s| s.as_str().unwrap())
            .collect();
        let err = assert_no_unknown_critical_extensions(&fixture["object"], &supported)
            .expect_err(&format!("{id} must be rejected"));
        assert_eq!(
            err.category(),
            fixture["expected_rejection"].as_str().unwrap(),
            "category mismatch for {id}"
        );
    }
}

#[test]
fn pinned_schema_digest_fixtures_match() {
    let doc = fixtures();
    for fixture in doc["schema_digest"].as_array().unwrap() {
        let id = fixture["id"].as_str().unwrap();
        let domain = fixture["domain"].as_str().unwrap();
        let pinned = fixture["pinned_schema_digest"].as_str().unwrap();
        let bytes = canonical::canonical_bytes_of_value(&fixture["schema"]).unwrap();
        let computed = canonical::digest(&bytes, domain).unwrap();
        let accepted = computed == pinned;
        match fixture["expected"].as_str().unwrap() {
            "accept" => assert!(accepted, "{id}: pinned schema digest must verify"),
            "reject" => assert!(
                !accepted,
                "{id}: altered pinned schema digest must fail closed"
            ),
            other => panic!("{id}: unknown expectation {other}"),
        }
    }
}
