#!/usr/bin/env bash
# Idempotent workspace bootstrap for Linux development hosts and Cursor Cloud
# Agent pods. Referenced by `.cursor/environment.json` (`install`) and usable
# directly on `DEV-LINUX-NATIVE-01`.
#
# Scope: dependency installation, toolchain warm-up, and docs-sync hook
# registration only. It starts no services, contacts no Provider, and reads no
# secret material.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# pnpm aborts with ERR_PNPM_ABORTED_REMOVE_MODULES_DIR_NO_TTY when it must purge
# node_modules without a TTY.
export CI="${CI:-true}"

log() { printf '[setup-dev-env] %s\n' "$*"; }

# --- TypeScript workspace ---------------------------------------------------
log "installing pnpm workspace dependencies"
if ! command -v pnpm >/dev/null 2>&1; then
  corepack enable
fi
pnpm install --frozen-lockfile

# --- Rust toolchain ---------------------------------------------------------
# rust-toolchain.toml pins the version; `cargo --version` makes rustup
# materialize it during install instead of on the first build.
log "resolving pinned Rust toolchain"
if command -v cargo >/dev/null 2>&1; then
  cargo --version
  cargo fetch --locked
else
  log "cargo not found; skipping Rust warm-up (Rust validation will be unavailable)"
fi

# --- docs-sync hooks --------------------------------------------------------
# `pnpm run hooks:install` sets core.hooksPath to .githooks, which would replace
# an agent-managed hooks directory instead of composing with it. Such
# dispatchers chain to `<git-dir>/hooks`, so write forwarders there and never
# touch the managed directory itself.
install_forwarder() {
  local hook_name="$1"
  local hooks_dir="$2"
  mkdir -p "$hooks_dir"
  rm -f "$hooks_dir/$hook_name"
  cat >"$hooks_dir/$hook_name" <<EOF
#!/bin/sh
# Generated by scripts/setup-dev-env.sh: forwards to the repository docs-sync
# gate so it also runs when core.hooksPath points at a managed hooks directory.
exec "\$(git rev-parse --show-toplevel)/.githooks/$hook_name" "\$@"
EOF
  chmod +x "$hooks_dir/$hook_name"
}

configured_hooks_path="$(git config --get core.hooksPath || true)"
git_dir_hooks="$(git rev-parse --absolute-git-dir)/hooks"
if [ -z "$configured_hooks_path" ]; then
  log "registering .githooks as core.hooksPath"
  git config core.hooksPath .githooks
else
  log "core.hooksPath is managed elsewhere; installing forwarders in $git_dir_hooks"
  install_forwarder pre-commit "$git_dir_hooks"
  install_forwarder pre-push "$git_dir_hooks"
fi

log "done"
